# Use the prairielearn r autograder
FROM ubcmds/base-r:fc31fb0

# Define additional packages that are specific to this course
ENV R_PACKAGES="infer"

# Install the pre-defined R packages
RUN install2.r -e $R_PACKAGES

# End course image